-- 코드를 입력하세요
SELECT DISTINCT OS1.USER_ID, OS1.PRODUCT_ID
FROM ONLINE_SALE OS1, ONLINE_SALE OS2
WHERE OS1.USER_ID = OS2.USER_ID and OS1.PRODUCT_ID = OS2.PRODUCT_ID and OS1.SALES_DATE != OS2.SALES_DATE
ORDER BY OS1.USER_ID, OS1.PRODUCT_ID DESC;